### ISSUE TITLE
Should we skip T2 and Prosody if T1 is deemed to be noisy or the like?

### ISSUE THREAD

**Issue by tjmahr** [LearningToTalk/NonWordTranscription#46]
Here's a comment that was in the code. Looks like a feature request to allow transcribers to skip T2 if T1 is untranscribable.

```
				# [SCORE T1]
				if trans_node$ == trans_node_t1_score$
					selectObject(transBasename$)
					segmentInterval = Get interval at time: transcription_textgrid.target1_seg, segmentXMid
					Set interval text: transcription_textgrid.target1_seg, segmentInterval, transcribe_segment.transcription$
					trans_node$ = trans_node_t2$
				endif
####  Issue: Should we skip T2 and Prosody if T1 is deemed to be noisy or the like?

				# [TRANSCRIBE T2]
				if trans_node$ == trans_node_t2$
					@transcribe_segment(trialNumber$, targetNonword$, target1$, target2$, 2)
					@next_back_quit(transcribe_segment.result_node$, trans_node_t2_score$, "", trans_node_quit$)				
					trans_node$ = next_back_quit.result$
					if trans_node$ != trans_node_quit$
						transcription2$ = transcribe_segment.segmentTranscription$
					endif
				endif
```

I'm removing the comment and creating an issue it for it. (Github is a more appropriate place for this kind of note.)

**Comment by marybeckman** [comment]
This was a question that we asked early on, but the answer was clear.  The transcribers want to be able to make this decision about whether a production is too noisy to transcribe, etc., on a segment-by-segment basis, and even separately for the segmental features and the prosodic position feature.  So this issue is closed and I should have deleted the comment before Franzo started re-coding for the new prosody protocol.   Thanks for cleaning that up, Tristan.
